language: en

reviews:
  profile: assertive
  high_level_summary: true
  poem: false
  auto_review:
    enabled: true
    drafts: true

  tools:
    golangci-lint:
      enabled: true
    gitleaks:
      enabled: true
    yamllint:
      enabled: true
    actionlint:
      enabled: true
    shellcheck:
      enabled: true
    markdownlint:
      enabled: true
    osvScanner:
      enabled: true
