language: en

reviews:
  profile: assertive
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false

  tools:
    golangci-lint:
      enabled: true
    gitleaks:
      enabled: true
    yamllint:
      enabled: true
